Repository canonical/ubuntu-com-security-api, pull requests merged in 2024-07, with the labels that each got.

#162 Fix empty status bug
  tests/test_routes.py
  webapp/views.py
Labels: Review: Code needed, Review: QA needed

#161 Created endpoint for serving upsert requests
  konf/raw-site-updates.yaml
  tests/test_routes.py
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#163 Created endpoint with smaller notices
  tests/test_routes.py
  webapp/app.py
  webapp/schemas.py
  webapp/views.py
Labels: Review: Code +1, Review: QA +1

#168 Add get_page_notices to swagger
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#169 Create numeric cves
  README.md
  migrations/versions/5df43dc932dd_.py
  tests/__init__.py
  tests/fixtures/models.py
  tests/test_commands.py
  tests/test_routes.py
  webapp/app.py
  webapp/commands.py
  webapp/models.py
  webapp/schemas.py
  webapp/views.py
Labels: Review: QA +1, Review: Code +1 (with changes)

#170 Limit notices requests to 20 at most
  tests/test_routes.py
  webapp/views.py
Labels: Review: Code +1, Review: QA +1
